POST http://localhost:3003/api/blogs
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtheXR0YWphMiIsImlkIjoiNjFiMTAxNGZiY2ZkMTRlMGU2NTZjOWUzIiwiaWF0IjoxNjM5OTI2NTI1LCJleHAiOjE2Mzk5MzAxMjV9.Bai7jiPpUYm_n_DSvPhDtZvAQJwFJQZuYrCKqVJuDRw

{
  "title": "This is post num 1 authorized by kayttaja2",
  "author": "Google",
  "url": "https://www.google.fi/",
  "likes": 6
}